Repository macroenergy/MacroEnergy.jl, pull requests merged in 2025-05, with the labels that each got.

#68 Switch MacroEnergySystemsScaling -> MacroEnergyScaling
  Project.toml
  src/MacroEnergy.jl
Labels: bug

#71 Merge user guides on Commodities, Nodes, Locations, System
  docs/make.jl
  docs/src/Manual/Commodities.md
  docs/src/Manual/TimeData.md
  docs/src/User Guide/user_add_asset.md
  docs/src/User Guide/user_add_commodity.md
  docs/src/User Guide/user_add_location.md
  docs/src/User Guide/user_add_node.md
  docs/src/User Guide/user_asset_constraints.md
  docs/src/User Guide/user_build_model.md
  docs/src/User Guide/user_build_system.md
  docs/src/User Guide/user_policy_constraints.md
Labels: documentation

#73 How to contribute guide
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  docs/src/how_to_contribute.md
Labels: documentation

#76 Add policy constraints documentation
  docs/make.jl
  docs/src/User Guide/user_build_system.md
  docs/src/User Guide/user_policy_constraints.md
Labels: documentation

#77 Add documentation for configuring settings
  docs/make.jl
  docs/src/User Guide/user_settings.md
Labels: documentation

#80 Add write results guide
  docs/src/Guides/User Guide/5_output.md
  docs/src/Guides/User Guide/user_write_results.md
Labels: documentation

#81 Pre-release docs update #4
  README.md
  docs/make.jl
  docs/src/Guides/User Guide/5_output.md
  docs/src/Guides/User Guide/user_write_results.md
  docs/src/index.md
Labels: documentation

#69 Update template functions
  src/MacroEnergy.jl
  src/load_inputs/default_system_data.jl
  src/load_inputs/load.jl
  src/model/assets/battery.jl
  src/model/assets/beccselectricity.jl
  src/model/assets/beccsgasoline.jl
  src/model/assets/beccshydrogen.jl
  src/model/assets/beccsliquidfuels.jl
  src/model/assets/beccsnaturalgas.jl
  src/model/assets/co2injection.jl
  src/model/assets/electricdac.jl
  src/model/assets/electrolyzer.jl
  src/model/assets/fossilfuelsupstream.jl
  src/model/assets/fuelcell.jl
  src/model/assets/fuelsenduse.jl
  src/model/assets/gasstorage.jl
  src/model/assets/hydrores.jl
  src/model/assets/mustrun.jl
  src/model/assets/natgasdac.jl
  src/model/assets/powerline.jl
  src/model/assets/syntheticliquidfuels.jl
  src/model/assets/syntheticnaturalgas.jl
  src/model/assets/thermalhydrogen.jl
  src/model/assets/thermalhydrogenccs.jl
  src/model/assets/thermalpower.jl
  src/model/assets/thermalpowerccs.jl
  src/model/assets/vre.jl
  src/model/networks/location.jl
  src/model/system.jl
  src/utilities/model_templates.jl
Labels: bug, enhancement

#82 Add introductions and User guide on creating Assets
  docs/make.jl
  docs/src/Getting Started/1_overview.md
  docs/src/Guides/User Guide/user_add_asset.md
  docs/src/Guides/User Guide/user_add_location.md
  docs/src/Guides/guides_introduction.md
  docs/src/Tutorials/tutorials_introduction.md
  docs/src/how_to_contribute.md
Labels: documentation

#83 Pre-release docs update #5
  docs/make.jl
  docs/src/Getting Started/1_overview.md
  docs/src/Guides/User Guide/user_add_asset.md
  docs/src/Guides/User Guide/user_add_location.md
  docs/src/Guides/guides_introduction.md
  docs/src/Tutorials/tutorials_introduction.md
  docs/src/how_to_contribute.md
Labels: documentation

#84 Add utility functions to Macro API for modelers
  src/model/constraints/constraints_utils.jl
  src/model/networks/asset.jl
  src/model/networks/edge.jl
  src/model/networks/vertex.jl
  src/model/system.jl
Labels: enhancement

#85 Add new pages to modeler guide
  docs/Project.toml
  docs/make.jl
  docs/src/Guides/Modeler Guide/1_introduction.md
  docs/src/Guides/Modeler Guide/3_create_example_case.md
  docs/src/Guides/Modeler Guide/doctest/assets/electricity_stor.json
  docs/src/Guides/Modeler Guide/doctest/assets/electrolyzer.json
  docs/src/Guides/Modeler Guide/doctest/assets/h2pipelines.json
  docs/src/Guides/Modeler Guide/doctest/assets/naturalgas_power.json
  docs/src/Guides/Modeler Guide/doctest/assets/nuclear_power.json
  docs/src/Guides/Modeler Guide/doctest/assets/powerlines.json
  docs/src/Guides/Modeler Guide/doctest/assets/vre.json
  docs/src/Guides/Modeler Guide/doctest/settings/macro_settings.json
  docs/src/Guides/Modeler Guide/doctest/system/Period_map.csv
  docs/src/Guides/Modeler Guide/doctest/system/availability.csv
  docs/src/Guides/Modeler Guide/doctest/system/commodities.json
  docs/src/Guides/Modeler Guide/doctest/system/demand.csv
  docs/src/Guides/Modeler Guide/doctest/system/fuel_prices.csv
  docs/src/Guides/Modeler Guide/doctest/system/locations.json
  docs/src/Guides/Modeler Guide/doctest/system/nodes.json
  docs/src/Guides/Modeler Guide/doctest/system/time_data.json
  docs/src/Guides/Modeler Guide/doctest/system_data.json
  docs/src/Guides/Modeler Guide/modeler_build_asset.md
  docs/src/Guides/Modeler Guide/modeler_build_sectors.md
  docs/src/Guides/Modeler Guide/modeler_create_example_case.md
  docs/src/Guides/Modeler Guide/modeler_debugging_testing.md
  docs/src/Guides/Modeler Guide/modeler_es_graph.md
  docs/src/Guides/Modeler Guide/modeler_introduction.md
  docs/src/Guides/Modeler Guide/modeler_workflow.md
  docs/src/References/2_reading_input.md
  docs/src/References/5_utilities.md
  docs/src/images/locations_and_assets.png
  docs/src/images/nodes_and_edges.png
  src/load_inputs/load_system.jl
  src/model/constraints/constraints_utils.jl
  src/model/networks/asset.jl
  src/model/networks/edge.jl
  src/model/networks/vertex.jl
  src/model/system.jl
Labels: documentation

#91 Update 1_overview.md
  docs/src/Getting Started/1_overview.md
Labels: documentation
